services:
  mongodb:
    image: mongo:7.0
    container_name: forum-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=forumdb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: forum-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  forum-app:
    build: .
    container_name: forum-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/forumdb?authSource=admin
      - DB_TYPE=mongodb
    depends_on:
      - mosquitto
      - mongodb
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  mongodb_data:
  mosquitto_data:
  mosquitto_log:
