version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: forum-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  forum-app:
    build: .
    container_name: forum-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
